---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Install ec2 Instance
      ec2:
        access_key: "{{ AccessKey }}"
        secret_key: "{{ SecretKey }}"
        key_name: priya
        instance_type: t2.micro
        region: us-east-1
        image: ami-0c293f3f676ec4f90
        wait: yes
        count: 1
        vpc_subnet_id: subnet-0d2a479cc5ddd7c51
        assign_public_ip: yes

