---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Terminate ec2
      ec2:
        access_key: "{{ AccessKey }}"
        secret_key: "{{ SecretKey }}"
        instance_ids: i-012b32314808d4d25
        state: absent
